### PR TITLE
feat: reduce prettier print width to 100

### PR DESCRIPTION
**Pull request by ForbesLindesay**
I know this is a bit of a personal taste thing, but I've found a few times that I end up wondering why prettier isn't wrapping a very long line. If this were a lint rule, I'd want it to be even higher, but because prettier aims to fill the full available width, I think it would be better to reduce it slightly.

### CODE REVIEW

**Comment by WoodyWoodsta** [comment]
Is there a way to tell prettier to wrap lists and attrs etc after a certain number, if the line does not exceed the length restriction? I run into this feeling as well, where I'm 6 destructured imports in and it's not doing what I would expect. I think the airbnb guide recommends at most 3 items before positioning them vertically.

**Comment by WoodyWoodsta** [comment]
Doing some reading into this and it appears the behaviour is dependant on how you type it originally, giving you a choice as opposed to it being a hard rule - https://prettier.io/docs/en/rationale.html#multi-line-objects

**Comment by ForbesLindesay** [comment]
The only global control prettier provides for this is the line length, but because it's automated and not a lint rule, it's not like you have to worry about manually breaking out a line that's naturally long and awkward to separate.

For some cases, like objects, it can pick it up based on what you type, but for other things it will refuse to let you break it over multiple lines unless it would be over the character limit you specify.

**Pull request merged**
